import type { ReportData } from "@/types/business-analysis"

export async function generatePDF(report: ReportData): Promise<void> {
  // Dynamic import — jsPDF uses browser APIs, must not run during SSR
  const { jsPDF } = await import("jspdf")

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

  const primaryColor: [number, number, number] = [65, 84, 68] // #415444
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = margin

  const checkNewPage = (needed = 20) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage()
      y = margin
    }
  }

  const addText = (
    text: string,
    x: number,
    size: number,
    bold = false,
    color: [number, number, number] = [50, 50, 50]
  ) => {
    doc.setFontSize(size)
    doc.setFont("helvetica", bold ? "bold" : "normal")
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, contentWidth - (x - margin))
    doc.text(lines, x, y)
    y += (lines as string[]).length * (size * 0.38) + 3
  }

  // ── Header bar ──────────────────────────────────────────────
  doc.setFillColor(...primaryColor)
  doc.rect(0, 0, pageWidth, 28, "F")
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(255, 255, 255)
  doc.text("Ecozon — Sustainability Report", margin, 18)
  y = 36

  // ── Business info ────────────────────────────────────────────
  addText(report.business.name, margin, 15, true, primaryColor)
  addText(
    `Industry: ${report.business.industry}  |  Size: ${report.business.size}  |  Date: ${new Date(report.analysis_date).toLocaleDateString()}`,
    margin, 9
  )
  addText(report.business.description, margin, 10)
  y += 4

  // ── Executive Summary ────────────────────────────────────────
  checkNewPage(40)
  addText("Executive Summary", margin, 13, true, primaryColor)
  y += 1
  addText(report.executive_summary, margin, 10)
  y += 5

  // ── Estimated Total Reduction callout ────────────────────────
  checkNewPage(16)
  doc.setFillColor(232, 240, 232)
  doc.roundedRect(margin, y, contentWidth, 12, 3, 3, "F")
  doc.setFontSize(10)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...primaryColor)
  doc.text(`Estimated Total Reduction: ${report.estimated_total_reduction}`, margin + 4, y + 7.5)
  y += 18

  // ── Key Impact Areas ─────────────────────────────────────────
  checkNewPage(30)
  addText("Key Impact Areas Identified", margin, 13, true, primaryColor)
  y += 1

  report.impact_points.forEach((ip, i) => {
    checkNewPage(28)
    const severityColors: Record<string, [number, number, number]> = {
      high: [185, 28, 28],
      medium: [161, 98, 7],
      low: [21, 128, 61],
    }
    const sc = severityColors[ip.severity] ?? [80, 80, 80]

    addText(`${i + 1}. ${ip.title}`, margin, 11, true)
    doc.setFontSize(8)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(...sc)
    doc.text(`${ip.severity.toUpperCase()} severity  |  ${ip.area}  |  ${ip.estimated_impact}`, margin + 4, y)
    y += 5
    addText(ip.description, margin + 4, 9)
    y += 2
  })
  y += 4

  // ── Action Plan ──────────────────────────────────────────────
  checkNewPage(30)
  addText("Action Plan", margin, 13, true, primaryColor)
  y += 1

  report.action_plan.forEach((group) => {
    checkNewPage(20)
    addText(group.impact_area, margin, 11, true)

    group.actions.forEach((action, i) => {
      checkNewPage(35)
      addText(`  ${i + 1}. ${action.title}`, margin, 10, true)
      addText(action.description, margin + 6, 9)

      doc.setFontSize(8)
      doc.setFont("helvetica", "normal")
      doc.setTextColor(100, 100, 100)
      doc.text(
        `Difficulty: ${action.difficulty}  |  Impact: ${action.impact}  |  Timeline: ${action.timeline}  |  Reduction: ${action.estimated_reduction}`,
        margin + 6,
        y
      )
      y += 8
    })
    y += 3
  })

  // ── Next Steps ───────────────────────────────────────────────
  checkNewPage(30)
  addText("Recommended Next Steps", margin, 13, true, primaryColor)
  y += 1

  report.next_steps.forEach((step, i) => {
    checkNewPage(12)
    addText(`${i + 1}. ${step}`, margin, 10)
  })

  // ── Footer on every page ─────────────────────────────────────
  const totalPages = (doc as any).getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    doc.setFontSize(7)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(160, 160, 160)
    doc.text(
      `Generated by Ecozon  |  Page ${p} of ${totalPages}`,
      margin,
      pageHeight - 8
    )
  }

  const fileName = `${report.business.name.replace(/[^a-z0-9]/gi, "_")}_sustainability_report.pdf`
  doc.save(fileName)
}
